# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.client:
        class: AppBundle\Meetup\Client
        arguments:
            - '@httplug.client'
            - '@serializer'
        public: false

    app.cached_client:
        class: AppBundle\Meetup\CachedClient
        decorates: app.client
        arguments:
            - '@app.cached_client.inner'
            - '@cache.app'
        public: false

    app.gateway:
        class: AppBundle\Meetup\Gateway
        arguments:
            - '@app.client'
            - '@doctrine.orm.default_entity_manager'
            - '@logger'

    app.group_request_workflow_listener:
        class: AppBundle\Meetup\GroupRequestWorkflowListener
        arguments:
            - '@app.mailer'
        tags:
            - name: kernel.event_subscriber
        public: false

    app.mailer:
        class: AppBundle\Meetup\Mailer
        arguments:
            - '@mailer'
            - '@twig'
            - '%app.admin_mail%'

    app.meetup_group_validator:
        class: AppBundle\Validation\MeetupGroupValidator
        arguments:
            - '@app.client'
        tags:
            - name: validator.constraint_validator
        public: false

    property_normalizer:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        arguments:
            - ~
            - '@serializer.name_converter.camel_case_to_snake_case'
        tags:
            - name: serializer.normalizer
